framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    session:
        handler_id: null
        cookie_lifetime: 604800
        cookie_secure: auto
        cookie_samesite: lax

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
