parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Redis:
        class: Redis
        calls:
            - connect:
                  - '%env(REDIS_HOST)%'
                  - '%env(REDIS_PORT)%'
            - select:
                  - '%env(REDIS_SESSION_DB)%'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'

    App\Service\Email\EmailSender:
        arguments:
            $fromEmail: '%env(MAILER_SENDER_EMAIL)%'
            $fromName: '%env(MAILER_SENDER_NAME)%'